### ISSUE TITLE
Why do we need a ones layer when extracting features?

### ISSUE THREAD

**Issue by lklkyu** [leekwoon/KR-DL-UCT#3]
![image](https://github.com/leekwoon/KR-DL-UCT/assets/53509707/b4aa7728-983c-4218-99f7-5e8cfe33e3d2)
Why do we need a ones layer when extracting features?

**Comment by leekwoon** [comment]
Hi, we refer it from AlphaGo paper which first suggest just in case all other features has zero values. 

Please let me know if you have an any further questions!
